spring:
  profiles:
    active: local
---
spring:
  profiles: local
  kafka:
    consumer:
      bootstrap-servers: localhost:9093,localhost:9094,localhost:9095
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer 
      group-id: library-events-listener-group
      
---
spring:
  profiles: nonprod
  kafka:
    consumer:
      bootstrap-servers: localhost:9093,localhost:9094,localhost:9095
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer 
      group-id: library-events-listener-group

---
spring:
  profiles: prod
  kafka:
    consumer:
      bootstrap-servers: localhost:9093,localhost:9094,localhost:9095
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer 
      group-id: library-events-listener-group
      
